import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import HomeCategory from "../components/HomeCategory";
import { useDispatch } from "react-redux";
import { setDataToSearchFrom } from "../features/searchBar/searchBarSlice";

export default function Home({
  recAll,
  animations,
  adventures,
  comedies,
  thrillers,
  searchBarData,
}) {
  // console.log(searchBarData);
  const dispatch = useDispatch();
  dispatch(setDataToSearchFrom(searchBarData));
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" min-h-[calc(100vh-140px)] my-0 mx-auto max-w-7xl p-8 box-border">
        <HomeCategory movieGenre={recAll} />
        <HomeCategory movieGenre={animations} category={"animation"} />
        <HomeCategory movieGenre={adventures} category={"aventure"} />
        <HomeCategory movieGenre={comedies} category={"comédies"} />
        <HomeCategory movieGenre={thrillers} category={"thrillers"} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  let dataToSend = [];
  try {
    const { data } = await axios.get("http://localhost:3000/api/movies/");
    // console.log(data);
    dataToSend = data.data;
  } catch (error) {
    console.log("catch home>>", error);
  }
  // console.log(dataToSend);
  return { props: dataToSend };
}
