import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
import Link from "next/link";

export default function Home({ data }) {
  // console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          minHeight: "calc(100vh - 140px)",
          padding: "35px",
          boxSizing: "border-box",
          margin: "0 auto",
          maxWidth: "1200px",
        }}
      >
        <div style={{ display: "flex", flexWrap: "wrap", gap: "25px" }}>
          {data.map((movie) => {
            return (
              <Link
                href={`/movie/${movie._id}`}
                key={movie._id}
                style={{ width: "calc(100%/4 - 75px /4)" }}
              >
                <h2>{movie.original_title}</h2>
                <Image
                  src={`https://image.tmdb.org/t/p/original${movie.poster_path}`}
                  alt={`Affiche du film ${movie.original_title}`}
                  width={150}
                  height={200}
                />
              </Link>
            );
          })}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  let dataToSend = [];
  try {
    const { data } = await axios.get("http://localhost:3000/api/movies/");
    // console.log(data);
    dataToSend = data.data;
  } catch (error) {
    console.log("catch home>>", error);
  }
  // console.log(dataToSend);
  return { props: { data: dataToSend } };
}
